### PR TITLE
Update Publications.md , changing DOI to links

### PR DESCRIPTION
**Pull request by cloner0110**

### CODE REVIEW

**Comment by philipcardiff** [comment]
Thanks @cloner0110.

This looks good.

As the DOI may be of interest (not just as a link), I suggest you display the DOI rather than use the word "Link"; I think the easiest way to do this would be to use `< >` as follows:
```
[Link](https://doi.org/10.1016/j.apm.2021.09.009)
```
becomes
```
<https://doi.org/10.1016/j.apm.2021.09.009>
```
For example, <https://doi.org/10.1016/j.apm.2021.09.009> instead of [Link](https://doi.org/10.1016/j.apm.2021.09.009).

You could use find+replace to change `[Link](` to `<` and then `)` to `>` (the second one needs more manual input to replace the correct ones).

What do you think?

**Comment by cloner0110** [comment]
@philipcardiff Yes, I thought of that also, but clicking on DOI will redirect them to the same page (publication page). In the case of someone who wants to copy the DOI, yes, what you mentioned is easier. 

One other option is that we link the whole text (or title) to the doi, e.g., like Google Scholar:
Screenshot 2024-01-12 at 17 48 39

Both are ok with me, and chatgpt can handle the manpower needed for edits :D .

**Comment by philipcardiff** [comment]
Ah nice, ChatGPT; I need to change my mindset and start using it more for tasks like this!

I like the idea of hyperlinking the title; that sounds good to me, assuming ChatGPT can help with the manual labour.

**Comment by cloner0110** [comment]
Hi @philipcardiff, I modified the markdown, and now the titles are linked to the DOI. 

Tell me your thoughts.

**Comment by philipcardiff** [comment]
Excellent, now merged!

**Comment by philipcardiff** [comment]
Now online at https://www.solids4foam.com/about/Publications.html.

**Comment by philipcardiff** [comment]
Hi @cloner0110, I noticed the last publication (Tukovic et al) gets truncated (maybe a ChatGPT max word count); can you double-check this? Thanks!

**Comment by cloner0110** [comment]
@philipcardiff, now it is fixed at https://github.com/solids4foam/solids4foam.github.io/pull/53 .

**Comment by philipcardiff** [comment]
Thanks again!

**Pull request merged**
